spring:
  jpa:
    show-sql:true
rabbitmq:
  statement:
    statement:
      queue: statement.statement.queue
    query:
      statement:
        queue: statement.query.statement.queue
logging:
  level:
    org:
      springframework:
        orm:
          jpa: debug

