spring:
  jpa:
    show-sql: true
  transaction:
    default-timeout: 60000
rabbitmq:
  register:
    fundloan:
      queue: register.fundloan.queue
    creditloan:
      queue: register.creditloan.queue
    debitloan:
      queue: register.debitloan.queue
    query:
      loan:
        id:
          queue: register.query.loan.id.queue
logging:
  level:
    org:
      springframework:
        orm:
          jpa: debug
