spring:
  jpa:
    show-sql: true
rabbitmq:
  account:
    createaccount:
      queue: account.createaccount.queue
    funding:
      queue: account.funding.queue
    validate:
      credit:
        queue: account.validate.credit.queue
      debit:
        queue: account.validate.debit.queue
    statementheader:
      queue: account.statementheader.queue
    loanstocycle:
      queue: account.loanstocycle.queue
    closeloan:
      queue: account.closeloan.queue
    query:
      account:
        id:
          queue: account.query.account.id.queue
      loan:
        id:
          queue: account.query.loan.id.queue
