rabbitmq:
  host: localhost
  port: 5672
  virtual-host: /
  password: guest
  username: guest
  exchange: merchloan.exchange
  account:
    createaccount:
      queue: account.createaccount.queue
      routing-key: account.createaccount.routingkey
    funding:
      queue: account.funding.queue
      routing-key: account.funding.routingkey
    query:
      account:
        id:
          queue: account.account.querybyid.queue
          routing-key: account.account.querybyid.routingkey
      loan:
        id:
          queue: account.loan.querybyid.queue
          routing-key: account.loan.querybyid.routingkey
  register:
    creditaccount:
      queue: register.creditaccount.queue
      routingkey: register.creditaccount.routingkey
    debitaccount:
      queue: register.debitaccount.queue
      routingkey: register.debitaccount.routingkey
    query:
      loan:
        id:
          queue: register.querybyloanid.queue
          routingkey: register.querybyloanid.routingkey
  servicerequest:
    queue: servicerequest.queue
    routingkey: servicerequest.routingkey
    query:
      id:
        queue: servicerequest.querybyid.queue
        routingkey: servicerequest.querybyid.routingkey
